### ISSUE TITLE
sometimes, it does not respect the modification dates[BUG]

### ISSUE THREAD

**Issue by soysanti** [T0biasCZe/AdbFileManager#10] opened 2023-07-31 11:52 UTC
sometimes, it does not respect the modification dates ( and write the date of the copy instead of when it was created)

![image](https://github.com/T0biasCZe/AdbFileManager/assets/17128285/2ad9f78c-b78f-496c-bff9-1017e4a1bd69)
****

mobile =HUAWEI P10
\WhatsApp\Media\WhatsApp Images
copying 4190 elements

If I copy it from windows explorer it works fine
some folders do respect dates, other folders from a date stop copying dates.
Maybe some file has problems copying and stops copying dates. If you need any debug tell me what to do. Thank you

EDIT: 
I'm doing tests compressing photos with APP and something similar happens to me.
Does the program compress anything?
If so, could you create a box so that it does not compress?
Thank you

**Comment by nezuky** [comment] 2023-08-01 04:18
> sometimes, it does not respect the modification dates

In my experience dates are only copied when transferring from `Phone -> PC`.
You will lose your modified date when transferring from `PC -> Phone`

Perhaps that's the cause of your issue.

**Comment by T0biasCZe** [comment] 2023-08-01 06:42
it doesnt copy PC -> Phone because ADB doesnt have flag for keeping modification dates when copying files to phobe, like with copying files to PC where you can use -a flag

**Comment by T0biasCZe** [comment] 2023-08-01 06:42
>  Does the program compress anything?

nah

**Comment by soysanti** [comment] 2023-08-02 13:49
thanks for answering.
I am trying to copy from MOBILE --> PC and today's date is overwritten a few times. I can't find the reason.

**Comment by soysanti** [comment] 2023-08-02 14:33
![image](https://github.com/T0biasCZe/AdbFileManager/assets/17128285/71fe439e-6084-4a9d-9f32-ef6fd77c2857)
Some conclusions that I can draw is that jpg files do not save the date and jpeg files do...
I will modify the extensions to check.

**Comment by soysanti** [comment] 2023-08-02 14:40
I have no idea about ADB, but I don't know if you can put "ADB Push"
https://forum.xda-developers.com/t/q-transfering-files-from-pc-how-to-keep-date-modified-stay-intact.1840238/

thanks

**Comment by T0biasCZe** [comment] 2023-08-02 17:02
I tested it, it copies the date modified for me when copying phone to pc
![image](https://github.com/T0biasCZe/AdbFileManager/assets/44525446/fdf08268-35f5-4192-9149-0e63ead9bd04)

and PC to phone should also work in v1.3.1

**Comment by soysanti** [comment] 2023-08-02 17:28
Aw....... yes it works perfectly. aaauuu

![image](https://github.com/T0biasCZe/AdbFileManager/assets/17128285/cbb9d772-9792-4b9f-8251-26791dd559b4)

I did not see this box.
It works perfectly and I am very happy because I had never been able to copy the dates from the DUAL section.
/storage/emulated/10/

So with this program I'm finally going to be able to have dates.

Thank you very much for sharing the program with everyone.

Greetings

**Closed** 2023-08-02 17:34 UTC
Labels: bug
